name: speedtestapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State Managment
  mobx: ^2.0.7+3

  #MobX's Widgets
  flutter_mobx: ^2.0.6+1

  #Mobx's annotations
  mobx_codegen: ^2.0.7

  #Json Converter
  json_serializable: ^6.2.0

  #Json Annotations
  json_annotation: ^4.5.0

  #Dependecy Injection 
  get_it: ^7.2.0

  #Dependency Injection Annotations
  injectable: ^1.5.3

  #Navigator
  go_router: ^4.1.0

  #Localization
  easy_localization: ^3.0.1

  #Device Capabilities
  flutter_screenutil: ^5.5.3+2

  #Network
  dio: ^4.0.6

  #Database
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  #Hashcode
  equatable: ^2.0.3

  #Random id 
  uuid: ^3.0.6

  #Theme
  flex_color_scheme: ^5.0.1
  cupertino_icons: ^1.0.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Generators
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.3

  #Lints
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
  #Localization assets
    - assets/translations/